# Generated by Django 4.2 on 2025-02-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'verbose_name': 'Контрольная точка', 'verbose_name_plural': 'Контрольные точки'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name': 'История болезни', 'verbose_name_plural': 'Истории болезни'},
        ),
        migrations.AlterModelOptions(
            name='surgicaloperation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='treatmentdrug',
            options={'verbose_name': 'Фармакотерапия', 'verbose_name_plural': 'Фармакотерапии'},
        ),
        migrations.RemoveField(
            model_name='clinicalstage',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='treatmentdrug',
            name='check_point_id',
        ),
        migrations.AddField(
            model_name='clinicalstage',
            name='check_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.checkpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='date_of_discharge',
            field=models.DateField(null=True, verbose_name='Дата выписки'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='date_of_receipt',
            field=models.DateField(null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='hospital_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_renal_denervation.hospital', verbose_name='ЛПУ'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app_renal_denervation.patient', verbose_name='ID пациента'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='app_renal_denervation.patient'),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='catheter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_renal_denervation.cathetertype', verbose_name='Тип катетера'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='dose',
            field=models.FloatField(null=True, verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.medicine', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='taking_medicine_day',
            field=models.BooleanField(verbose_name='Приём днём'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='taking_medicine_evening',
            field=models.BooleanField(verbose_name='Приём вечером'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='taking_medicine_morning',
            field=models.BooleanField(verbose_name='Приём утром'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='taking_medicine_night',
            field=models.BooleanField(verbose_name='Приём на ночь'),
        ),
    ]
