# Generated by Django 4.2 on 2025-02-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0002_alter_checkpoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacological_group',
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='pharmacological_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.pharmacologicalgroup', verbose_name='Фармакологическая группа'),
            preserve_default=False,
        ),
    ]
