# Generated by Django 4.2 on 2025-02-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0003_remove_medicine_pharmacological_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalstage',
            name='check_point',
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='check_point_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.checkpoint', verbose_name='ID контрольной точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdrug',
            name='check_point_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.checkpoint', verbose_name='ID контрольной точки'),
            preserve_default=False,
        ),
    ]
