# Generated by Django 4.2 on 2025-02-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0004_remove_clinicalstage_check_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicaloperation',
            name='type_stage',
            field=models.CharField(choices=[('До операции', 'До операции'), ('Повторная операция', 'Повторная операция')], default=1, verbose_name='Тип лечения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdrug',
            name='type_stage',
            field=models.CharField(choices=[('Фармакотерапия', 'Фармакотерапия')], default=1, verbose_name='Тип лечения'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClinicalStage',
        ),
    ]
