# Generated by Django 4.2 on 2025-02-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0005_surgicaloperation_type_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': 'Показатель исследования', 'verbose_name_plural': 'Показатели исследований'},
        ),
        migrations.AddField(
            model_name='metric',
            name='unit_for_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='app_renal_denervation.unit'),
        ),
        migrations.AlterField(
            model_name='cathetertype',
            name='shortname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сокращённое название катетера'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='measurement_type',
            field=models.CharField(choices=[('количественный', 'количественный'), ('качественный', 'качественный'), ('бинарный', 'бинарный'), ('описательный', 'описательный')], verbose_name='Тип измерямеого признака'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='reference_binary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Референсное значение для бинарного признака'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='reference_max_numerical',
            field=models.IntegerField(blank=True, null=True, verbose_name='Референсное значение по верхней границе количественного признака'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='reference_min_numerical',
            field=models.IntegerField(blank=True, null=True, verbose_name='Референсное значение по нижней границе количественного признака'),
        ),
        migrations.AlterField(
            model_name='metricstemplates',
            name='research_template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_templates', to='app_renal_denervation.researchtemplate'),
        ),
        migrations.AlterField(
            model_name='researchtemplate',
            name='type_research',
            field=models.CharField(blank=True, choices=[('laboratory', 'laboratory'), ('instrumental', 'instrumental')], null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='check_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app_renal_denervation.checkpoint', verbose_name='ID контрольной точки'),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='type_stage',
            field=models.CharField(choices=[('Операция', 'Операция'), ('Повторная операция', 'Повторная операция')], verbose_name='Тип лечения'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='check_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments_drugs', to='app_renal_denervation.checkpoint', verbose_name='ID контрольной точки'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='fullname',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Название единиц измерения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='shortname',
            field=models.CharField(max_length=256, verbose_name='Обозначение единиц изменения'),
        ),
        migrations.AlterField(
            model_name='variantqualitative',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_qualitative', to='app_renal_denervation.metric'),
        ),
        migrations.AlterField(
            model_name='variantqualitative',
            name='reference',
            field=models.BooleanField(verbose_name='Допустимое значение'),
        ),
    ]
