# Generated by Django 4.2 on 2025-02-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0006_alter_metric_options_metric_unit_for_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit_for_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='app_renal_denervation.unit', verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='metricstemplates',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.metric', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='metricstemplates',
            name='research_template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_templates', to='app_renal_denervation.researchtemplate', verbose_name='Шаблон исследования'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_binary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Значение бинарного признака'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_descriptive',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Значение описательного признака'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_numerical',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение количественного признака'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_qualitative_id',
            field=models.ManyToManyField(blank=True, null=True, to='app_renal_denervation.variantqualitative', verbose_name='Значение качественногоо признака'),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проводимого исследования'),
        ),
        migrations.AlterField(
            model_name='researchtemplate',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='researchtemplate',
            name='type_research',
            field=models.CharField(blank=True, choices=[('laboratory', 'laboratory'), ('instrumental', 'instrumental')], null=True, verbose_name='Тип исследования'),
        ),
        migrations.AlterField(
            model_name='variantqualitative',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_qualitative', to='app_renal_denervation.metric', verbose_name='Показатель'),
        ),
    ]
