# Generated by Django 4.2 on 2025-03-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0007_alter_metric_unit_for_metric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AblationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название места абляции')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Место абляиции',
                'verbose_name_plural': 'Места абляции',
            },
        ),
        migrations.CreateModel(
            name='PatientDesease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start_disease', models.IntegerField(verbose_name='Год начала заболевания')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание')),
                ('classification_disease', models.CharField(choices=[('Основное', 'Основное'), ('Сопуствующее', 'Сопуствующее')], verbose_name='Тип значимости заболевания')),
                ('disease_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_diseases', to='app_renal_denervation.disease', verbose_name='Заболевание пациента')),
            ],
            options={
                'verbose_name': 'Заболевание пациента',
                'verbose_name_plural': 'Заболевания пациента',
            },
        ),
        migrations.CreateModel(
            name='TypeCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название контрольной точки')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Тип контрольной точки',
                'verbose_name_plural': 'Типы контрольных точек',
            },
        ),
        migrations.AlterModelOptions(
            name='surgicaloperation',
            options={'verbose_name': 'Оперативное вмешательство', 'verbose_name_plural': 'Оперативные вмешательства'},
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='treatmentdrug',
            name='name',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='metric',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='metricstemplates',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='research',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='researchtemplate',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='researchtemplate',
            name='obligation_of_research',
            field=models.CharField(choices=[('Обязательное', 'Обязательное'), ('Необязательное', 'Необязательное')], default=1, verbose_name='Важность исследования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='number_of_ablation_points',
            field=models.IntegerField(default=1, verbose_name='Количество точек абляции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdrug',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='variantqualitative',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='date_of_discharge',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выписки'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='date_of_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_renal_denervation.hospital', verbose_name='ЛПУ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Город местонахождения ЛПУ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='shortname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Аббревиатура лечебно-профилактического учреждения'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='research_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_values', to='app_renal_denervation.research', verbose_name='Исследование'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='researchtemplate',
            name='type_research',
            field=models.CharField(blank=True, choices=[('Лабораторное', 'Лабораторное'), ('Инструментальное', 'Инструментальное')], null=True, verbose_name='Тип исследования'),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='catheter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_renal_denervation.cathetertype', verbose_name='Тип катетера'),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='date',
            field=models.DateField(verbose_name='Дата оперативного вмешательства'),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название оперативного вмешательства'),
        ),
        migrations.AlterField(
            model_name='treatmentdrug',
            name='dose',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза'),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.AddField(
            model_name='patientdesease',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diseases', to='app_renal_denervation.patient'),
        ),
        migrations.AddField(
            model_name='ablationsite',
            name='surgical_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ablation_sites', to='app_renal_denervation.surgicaloperation', verbose_name='ID операции'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='type_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='app_renal_denervation.typecheckpoint', verbose_name='Тип контрольной точки'),
        ),
    ]
