# Generated by Django 4.2 on 2025-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0008_ablationsite_patientdesease_typecheckpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathetertype',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='disease',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='code_ICD_10',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Код МКБ 10'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='shortname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Краткое название заболевания'),
        ),
    ]
