# Generated by Django 4.2 on 2025-04-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0010_alter_checkpoint_type_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='shortname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Краткое название показателя'),
        ),
        migrations.AlterField(
            model_name='patientdesease',
            name='classification_disease',
            field=models.CharField(choices=[('Основное', 'Основное'), ('Сопутствующее', 'Сопутствующее')], verbose_name='Тип значимости заболевания'),
        ),
    ]
