# Generated by Django 4.2 on 2025-05-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_renal_denervation', '0012_rename_patientdesease_patientdisease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricvalue',
            name='value_qualitative_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_renal_denervation.variantqualitative', verbose_name='Значение качественногоо признака'),
        ),
    ]
